pishshomare_bank = {
        '055': 'bank eghtesad novin',
        '054': 'bank parsian',
        '057': 'bank pasargad',
        '021': 'post bank iran',
        '018': 'bank tejarat',
        '051': 'moasese etebari tosee',
        '020': 'bank tosee saaderat',
        '013': 'bank refah',
        '056': 'bank saman',
        '015': 'bank sepah',
        '058': 'bank sarmaye',
        '019': 'bank saderat iran',
        '011': 'bank sanaat va madan',
        '053': 'bank kar afarin',
        '016': 'bank keshavarzi',
        '010': 'bank markazi jomhori eslami iran',
        '014': 'bank maskan',
        '012': 'bank melat',
        '017': 'bank meli iran',
        '065': 'bank hekmat',
        '062': 'bank ayandeh',
        '061': 'bank shahr',
        '066': 'bank dey',
        '078': 'bank khavarmiane',
        '063': 'bank ansar',
        '069': 'bank  iranzamin',
        '022': 'bank tosee va taavon',
        '064': 'bank gardeshgari',
        '070': 'bank resalat',
        '059': 'bank sina',
        '052': 'bank ghavamin',
        '080': 'bank noor',
        '060': 'bank mehriran',
        '079': 'bank mehreghtesad',
        '': ''

}

bank_pishshomare = {
        'bank eghtesad novin': '055',
        'bank parsian': '054',
        'bank pasargad': '057',
        'post bank iran': '021',
        'bank tejarat': '018',
        'moasese etebari tosee': '051',
        'bank tosee saaderat': '020',
        'bank refah': '013',
        'bank saman': '056',
        'bank sepah': '015',
        'bank sarmaye': '058',
        'bank saderat iran': '019',
        'bank sanaat va madan': '011',
        'bank kar afarin': '053',
        'bank keshavarzi': '016',
        'bank markazi jomhori eslami iran': '010',
        'bank maskan': '014',
        'bank melat': '012',
        'bank meli iran': '017',
        'bank hekmat': '065',
        'bank ayandeh': '062',
        'bank shahr': '061',
        'bank dey': '066',
        'bank khavarmiane': '078',
        'bank ansar': '063',
        'bank  iranzamin': '069',
        'bank tosee va taavon': '022',
        'bank gardeshgari': '064',
        'bank resalat': '070',
        'bank sina': '059',
        'bank ghavamin': '052',
        'bank noor': '080',
        'bank mehriran': '060',
        'bank mehreghtesad': '079',
        '': ''
}
num_bunk = {
         '1': 'bank keshavarzi', '2': 'bank tejarat', '3': 'bank refah', '4': 'bank saderat iran',
         '5': 'bank parsian', '6': 'bank mehriran', '7': 'bank meli iran', '8': 'bank melat',
         '': ''
}


